-- Sertifika doğrulama sistemi için Supabase tablo yapısı

-- PDF'li sertifikalar tablosu
CREATE TABLE public.cert_pdf (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  pdf_link text NULL DEFAULT ''::text,
  given text NULL DEFAULT ''::text,  -- Sertifika verilen kişi
  "from" text NULL DEFAULT ''::text,  -- Veren kurum
  date date NULL,  -- Sertifika tarihi
  uid text NULL DEFAULT ''::text,  -- Benzersiz kimlik
  cert_name text NULL DEFAULT ''::text,  -- Sertifika adı
  CONSTRAINT cert_pdf_pkey PRIMARY KEY (id),
  CONSTRAINT cert_pdf_created_at_key UNIQUE (created_at),
  CONSTRAINT cert_pdf_uid_key UNIQUE (uid)
) TABLESPACE pg_default;

-- PDF'siz sertifikalar tablosu
CREATE TABLE public.cert (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  creator text NULL DEFAULT ''::text,  -- Oluşturan kişi
  head text NULL DEFAULT ''::text,     -- Sertifika başlığı
  given text NULL DEFAULT ''::text,    -- Sertifika verilen kişi
  date date NULL,                      -- Sertifika tarihi
  file_id text NULL DEFAULT ''::text,  -- Dosya kimliği
  CONSTRAINT cert_pkey PRIMARY KEY (id),
  CONSTRAINT cert_file_id_key UNIQUE (file_id)
) TABLESPACE pg_default;

-- İndeksler
CREATE INDEX idx_cert_pdf_uid ON public.cert_pdf(uid);
CREATE INDEX idx_cert_pdf_given ON public.cert_pdf(given);
CREATE INDEX idx_cert_file_id ON public.cert(file_id);
CREATE INDEX idx_cert_given ON public.cert(given);

-- RLS (Row Level Security) politikaları
ALTER TABLE public.cert_pdf ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cert ENABLE ROW LEVEL SECURITY;

-- Herkese okuma izni (public access)
CREATE POLICY "Allow public read access cert_pdf" ON public.cert_pdf
    FOR SELECT USING (true);

CREATE POLICY "Allow public read access cert" ON public.cert
    FOR SELECT USING (true);

-- Sadece authenticated kullanıcılar yazabilir (admin paneli için)
CREATE POLICY "Allow authenticated insert cert_pdf" ON public.cert_pdf
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update cert_pdf" ON public.cert_pdf
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert cert" ON public.cert
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update cert" ON public.cert
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Örnek PDF sertifika verisi
INSERT INTO public.cert_pdf (
    pdf_link,
    given,
    "from",
    date,
    uid,
    cert_name
) VALUES 
(
    'https://example.com/certificate1.pdf',
    'Ahmet Yılmaz',
    'NAIN - Student Activity Network',
    '2024-12-15',
    'pdf_abc123def456',
    'Web Development Certificate'
),
(
    'https://example.com/certificate2.pdf',
    'Zeynep Kaya',
    'NAIN - Student Activity Network',
    '2024-11-20',
    'pdf_xyz789ghi012',
    'Data Science Certificate'
);

-- Örnek standart sertifika verisi
INSERT INTO public.cert (
    creator,
    head,
    given,
    date,
    file_id
) VALUES 
(
    'NAIN Admin',
    'Digital Marketing Workshop Certificate',
    'Mehmet Demir',
    '2024-10-10',
    'file_std001abc'
),
(
    'NAIN Admin',
    'Leadership Training Certificate',
    'Ayşe Öztürk',
    '2024-09-15',
    'file_std002def'
);
